# Generated by Django 4.2.5 on 2023-09-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_has_submitted_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='has_submitted_feedback',
        ),
        migrations.AddField(
            model_name='course',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
    ]
