# Generated by Django 4.2.5 on 2023-09-22 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_student_has_submitted_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_number', models.AutoField(primary_key=True, serialize=False)),
                ('date_submit_time', models.DateTimeField(auto_now_add=True)),
                ('feedback_message', models.TextField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.course')),
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
