# Generated by Django 4.2.5 on 2023-09-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_message',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Q1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Q2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Q3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Q4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Q5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
