# Generated by Django 4.2.5 on 2023-09-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_q1_alter_feedback_q2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Q1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Q2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Q3',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Q4',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Q5',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
