# Generated by Django 4.2.5 on 2023-10-13 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_contactsubmission'),
        ('feedback', '0005_feedback_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_number', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher'), ('chairperson', 'Chairperson')], default='student', max_length=20)),
                ('positive_percentage', models.FloatField()),
                ('negative_percentage', models.FloatField()),
                ('neutral_percentage', models.FloatField()),
                ('total_feedbacks', models.IntegerField()),
                ('report_message', models.TextField()),
                ('course_serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.course')),
                ('teacher_username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacher')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
